# Change these first
owner: flyingchewbacca # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Backup MX
    url: $BACKUPMX
  - name: Files
    url: $FILES
  - name: gotosocial
    url: $GOTOSOCIAL
  - name: Landing page
    url: $LANDINGPAGE
  - name: Matomo
    url: $MATOMO
  - name: Mail
    url: $MAIL
  - name: PrivateBin
    url: $PRIVATEBIN
  - name: Share
    url: $SHARE
  - name: Sysmikes Blog
    url: $SYSMIKESBLOG
  - name: Teamspeak
    check: "tcp-ping"
    url: $TEAMSPEAK
    port: 10011
  - name: vCard
    url: $VCARD
  - name: Webserver
    check: "tcp-ping"
    url: $WEBSERVER
    port: 443

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime**"
  introMessage: Status
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
